import TabMenuBtn from "@/components/tab-menu-btn";
import getSession from "@/lib/session";
import type { Metadata } from "next";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Welcome Tweet",
  description: "Generated by create next app",
};

export default async function TwwetLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const logout = async () => {
    "use server";

    const session = await getSession();
    if(session.id){
      session.destroy();
    }

    redirect('/login');
  }

  return (
    <div className={`bg-slate-100 flex flex-col h-screen`}>
      <div className="flex flex-col gap-3 pt-4 border-b border-black shadow-lg shadow-slate-100-100">
        <div className="flex justify-between items-center *:w-full px-5">
          <h1 className="text-center font-bold text-xl">Hello 김테스트1</h1>
        </div>
        <div className="flex w-full *:w-full *:py-2 *:text-center">
          <TabMenuBtn href='/' menuName="List" />
          <TabMenuBtn href='/profile' menuName="Profile" />
        </div>
      </div>
      {children}
    </div>
  );
}
