import TabMenuBtn from "@/components/tab-menu-btn";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Welcome Tweet",
  description: "Generated by create next app",
};

export default function TwwetLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className={`bg-slate-100 flex flex-col h-screen`}>
      <div className="flex flex-col gap-3 pt-4 border-b border-black shadow-lg shadow-slate-100-100">
        <h1 className="text-center font-bold text-xl">Hello 김테스트1</h1>
        <div className="flex w-full *:w-full *:py-2 *:text-center">
          <TabMenuBtn href='/' menuName="List" />
          <TabMenuBtn href='/profile' menuName="Profile" />
        </div>
      </div>
      {children}
    </div>
  );
}
